spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/productservice?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: false
    hibernate:
     ddl-auto: update
